### PR TITLE
Update UserCommands.cpp

### PR DESCRIPTION
**Pull request by LincolnBryant**
I've been convinced that the API should only allow the more restrictive set of characters. @matyasselmeci points out that `condor_q` with a numeric ID is going to be interesting...

### CODE REVIEW

**Comment by LincolnBryant** [comment]
added the other characters into the acceptable characters string. thanks @cnweaver

**Comment by cnweaver** [comment]
LGTM

**Comment by cnweaver** [comment]
Oh, but it might be good to update the comment to describe the new, equivalent regex.

**Comment by LincolnBryant** [comment]
Will do.

**Comment by LincolnBryant** [comment]
Going to finally merge this guy, too since I'm already rooting around in here,

**Pull request merged**
