### PR TITLE
add /protected

### PR DESCRIPTION
**Pull request by jlstephen**

### CODE REVIEW

**Comment by LincolnBryant** [comment]
we first need to mount /protected on all of the logins before pushing this change out

**Comment by jlstephen** [comment]
Has /protected been mounted everywhere yet so that this can be merged?

**Comment by LincolnBryant** [comment]
Mounted on l04/l05, stash-w, stash. I think it's good to go?

**Comment by LincolnBryant** [comment]
made all of the protected dirs. will actually merge tomorrow am

**Pull request merged**
